# Generated by Django 3.0.3 on 2020-02-17 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlueConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='default', max_length=254)),
                ('max_dpu_standard', models.IntegerField(default=300)),
                ('max_concurrent_jobs', models.IntegerField(default=50, help_text='No of concurrant job runs.')),
                ('cool_off_time', models.IntegerField(default=600, help_text='Wait time to resume launching glue jobs after hitting hot launch limit')),
                ('hot_launch_limit', models.IntegerField(default=10, help_text='Number of glue jobs that can be launched within cool off time.')),
                ('job_status_check_interval', models.IntegerField(default=60, help_text='Seconds')),
            ],
        ),
        migrations.CreateModel(
            name='GlueJob',
            fields=[
                ('job_uuid', models.UUIDField(default=uuid.UUID('1af155e6-e50f-4911-8bcb-91219ff0f35e'), primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='UNNAMED', max_length=254)),
                ('job_name', models.CharField(max_length=254)),
                ('requested_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('job_run_id', models.CharField(blank=True, max_length=25, null=True)),
                ('worker_type', models.IntegerField(choices=[(0, 'Standard'), (1, 'G1.X'), (2, 'G2.X')], default=0)),
                ('dpu', models.IntegerField(default=2)),
                ('status', models.IntegerField(choices=[(0, 'QUE'), (1, 'STARTING'), (2, 'RUNNING'), (3, 'TIMEOUT'), (4, 'FAILED'), (5, 'STOPPED'), (6, 'STOPPING'), (7, 'SUCCEEDED')])),
                ('trial_no', models.IntegerField(default=1)),
                ('message', models.TextField(max_length=1024)),
                ('preceding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preceding_job', to='core.GlueJob')),
                ('succeeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succeeding_job', to='core.GlueJob')),
            ],
        ),
        migrations.CreateModel(
            name='GlueArguments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=254)),
                ('glue_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GlueJob')),
            ],
        ),
    ]
