# Generated by Django 3.0.3 on 2020-02-17 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gluejob',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gluejob',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gluejob',
            name='job_uuid',
            field=models.UUIDField(default=uuid.UUID('de77319c-739f-423d-bf87-2023ea7de82a'), primary_key=True, serialize=False),
        ),
    ]
