# Generated by Django 3.0.3 on 2020-02-18 13:35

import apps.account.models.account
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default=apps.account.models.account.account_config_default)),
            ],
        ),
    ]
