# Generated by Django 3.0.3 on 2020-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aws_region',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
