# Generated by Django 3.0.3 on 2020-02-18 15:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlueJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_property', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('command', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('default_arguments', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('max_retries', models.IntegerField()),
                ('allocated_capacity', models.IntegerField()),
                ('timeout', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('glue_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GlueJobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('received_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField()),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], max_length=255)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('predecessor_runs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('allocated_capacity', models.IntegerField()),
                ('execution_time', models.IntegerField(blank=True, null=True)),
                ('timeout', models.IntegerField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('log_group_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glue.GlueJob')),
            ],
        ),
    ]
