# Generated by Django 3.0.3 on 2020-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gluejob',
            name='role',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
