# Generated by Django 3.0.3 on 2020-02-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_aws_region'),
        ('glue', '0002_gluejob_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gluejob',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
    ]
