# Generated by Django 3.0.3 on 2020-02-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0004_auto_20200219_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gluejobrun',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
