# Generated by Django 3.0.3 on 2020-02-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0006_auto_20200219_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gluejobrun',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('G1.X', 'G1 X'), ('G2.X', 'G2 X')], max_length=255, null=True),
        ),
    ]
